"""
Prepare SMW
"""


from madpy.conf import conf
from madpy.logger import G

import madpy.smw

def hook_define_args(parser):
    """
    Set the arguments for 'set'
    """
    madpy.smw.define_args(parser)

#SWM_DATATYPES
def run(args):
    """ Sync data types from SMW  """

    G.critical("Not quite implemented yet - ask Mark")
    sys.exit(0)
    site = madpy.smw.get_site(args)
    for page in site.Categories['MadProperty']:
        print '-' * 80
        text = page.edit()
        print text


    #{{#ask: [[Category:MadProperty]] 

    # for dt in conf.datatypes:
    #     dti = conf.datatypes[dt]
    #     prop_name = "Property:%s" % dt
    #     page = site.Pages[prop_name]
    #     ptxt = page.edit()
    #     if (not args.force) and len(ptxt) > 0:
    #         G.warning("Ignoring %s - property page already has content" % prop_name)
    #         continue

    #     ptxt = []
        
    #     if dti.has_key('help'):
    #         ptxt.append(dti.help + "\n")
    #     if dti.has_key('url'):
    #         ptxt.append("See: %s\n" % dti.url)
    #     if dti.has_key('smw_data_type'):
    #         ptxt.append("[[Has type::%s]]" % dti.smw_data_type)
    #     ptxt.append("[[Category:MadProperty]]")
    #     page.save("\n".join(ptxt), summary="Mad autogenerated Property page")
    #     G.warning("regenerated %s" % prop_name)
